### ISSUE TITLE
@nuxt/test-utils should have fewer peer dependencies

### ISSUE THREAD

**Issue by oskarols** [nuxt/test-utils#1019]
### Describe the feature

Hi! 👋 

We have peer dependency warnings coming from `@nuxt/test-utils` due to the fact that it requires peer dependencies for packages used by Nuxt.

```
➤ YN0002: │ NuxtExamplePackage doesn't provide h3 (p44b11), requested by @nuxt/test-utils.
➤ YN0002: │ NuxtExamplePackage doesn't provide nitropack (pc5e56), requested by @nuxt/test-utils.
➤ YN0002: │ NuxtExamplePackage doesn't provide vite (p9f68f), requested by @nuxt/test-utils.
➤ YN0002: │ NuxtExamplePackage doesn't provide vue (pf6e3c), requested by @nuxt/test-utils and other dependencies.
➤ YN0002: │ NuxtExamplePackage doesn't provide vue-router (p80fda), requested by @nuxt/test-utils.
```

It would be great if `@nuxt/test-utils` only had the bare minimum of peer dependencies. 🙏 

### Additional information

- [x] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [x] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [x] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
resolved in https://github.com/nuxt/test-utils/commit/4e10bd266a042120d7a4f8c30b515819e4d5bfc5.
