### ISSUE TITLE
Vue provide/inject is not testable in components

### ISSUE THREAD

**Issue by oskarols** [nuxt/test-utils#539]
Hi 👋 

We're experiencing issues with Nuxt plugins that utilize `vueApp.provide()` to inject values. Consuming those injected values in components works fine when using the dev server. However when testing with `nuxt-vitest` these values are not set.

We've tried to pass the nuxtApp.vueApp as `localVue` in the `mountSuspended()` options but this seems to have no effect.

I've created a failing test case for this [here](https://github.com/oskarols/nuxt-vitest/tree/test-app-injection) ([diff](https://github.com/danielroe/nuxt-vitest/compare/main...oskarols:nuxt-vitest:test-app-injection?expand=1))

The new component for the test case should look like this:

![image](https://github.com/danielroe/nuxt-vitest/assets/324147/5f101cf3-5f70-421a-9497-db68cdb5432d)

But in tests the content (which is the injected value) is empty.

**Comment by danielroe** [comment]
This workaround may help: https://github.com/nuxt/test-utils/issues/601#issuecomment-1837207080
