### ISSUE TITLE
enhancement: mocking $fetch before app starts (@sidebase/nuxt-auth)

### ISSUE THREAD

**Issue by niko-chaffinchicas** [nuxt/test-utils#547]
I've have run into use case that seems peculiar, but I wanted to pose it here in case it's something that would make sense to bundle into this package as an enhancement.

Put simply, I needed to do something like `registerEndpoint`, but to be able to set it up _before the Nuxt app starts_. We've tried calling `registerEndpoint` as early as possible, but from what I've seen, this just mocks calls for once the Vue app is mounted to the window, not before.

What I've landed on as a solution is have a Nuxt plugin that's only included for test runs which replaces the global `$fetch` with a mock implementation of `$fetch` wrapped in `vi.fn()`, plus a mock implementation of `$fetch.create`. That's coupled with an object that can be configured with the return values like so:

```ts
const endpointMocks = {
  'http://0.0.0.0:8000/api/1.0': {
    some: {
      endpoint: () => ({ ok: true }),
    },
  },
};
```

Right now it catches any call that doesn't match a path in this object, and raises an error instead of making a request.

Is this a feature that would be desirable to be included as part of `nuxt-vitest`? Or perhaps would this be better suited as its own module/package elsewhere?

**Comment by danielroe** [comment]
let's track this in https://github.com/nuxt/test-utils/issues/577.
