### ISSUE TITLE
devtools iframe not able to run in https

### ISSUE THREAD

**Issue by Clive-Ward-Cron** [nuxt/test-utils#548]
It would be preferable that the module use the protocol that is specified in either the vitest config or nuxt config.

https://github.com/danielroe/nuxt-vitest/blob/178c11865380b0cadb4c4af196486ebba308d3a9/packages/nuxt-vitest/src/module.ts#L49

This is resulting in the dev tools being unable to show the proper page for the ui:

![image](https://github.com/danielroe/nuxt-vitest/assets/23231126/8ac22c01-a078-4e2a-96b3-4a03f89e5d41)

**Comment by danielroe** [comment]
This is no longer replicable for me, so I think it must be resolved upstream.
