### ISSUE TITLE
renderSuspended renders layout AND component

### ISSUE THREAD

**Issue by StevenPewsey** [nuxt/test-utils#561]
I have a `NavigationBar` component that is rendered within a layout (`layouts/default.vue`)

I am wanting to test the NavigationBar in isolation of the rest of the page, but it contains the `NuxtLink` component so I need to test it within the context of the nuxt environment.

```ts
await renderSuspended(NavigationBar)
```

This is rendering the page as the following:

```html
<div
  id="__nuxt"
  data-v-app=""
>
  // my default layout with the `/` route rendered
</div>
<div>
  <div id="test-wrapper">
    // the NavigationBar component that I wanted to test
  </div>
</div>
```

Is this expected behaviour? In my case it is effectively rendering the `NavigationBar` twice as it's appearing with the `__nuxt` div in the layout, and in the `test-wrapper` div. This makes it hard to test using `@testing-library` as I can't use `getByText` but instead need to use `getAllbyText` as everything is rendered twice.

vitest version `0.32.2`
nuxt-vitest `0.10.5`

**Comment by danielroe** [comment]
This should now be implemented - we no longer render `app.vue` by default since https://github.com/nuxt/test-utils/pull/260.
