### ISSUE TITLE
Add option to set default route or mock app.vue

### ISSUE THREAD

**Issue by sky-code** [nuxt/test-utils#565]
I want to setup test environment without rendering my index page, please add config option for setting globally default route, for example '/test' instead of '/' or option to mock `app.vue` component.

So far I figured out workaround, in `nuxt.config.ts` I am doing mocking of index page manually with hooks

```
hooks: {
    'pages:extend'(pages: NuxtPage[]) {
      if (String(process.env?.TEST) === 'true') {
        const indexPage = pages.find((page) => page.name === 'index')
        const testPage = pages.find((page) => page.name === 'test')
        if (indexPage != null && testPage != null) {
          indexPage.file = testPage.file
        }
      }
    },
  },
```

Note this hook is not working when placed in `vitest.config.ts` overrides because function is not serializable.

**Comment by danielroe** [comment]
This should now be implemented - we no longer render `app.vue` by default since https://github.com/nuxt/test-utils/pull/260.
