### ISSUE TITLE
Vue-I18n not loaded

### ISSUE THREAD

**Issue by Floppy012** [nuxt/test-utils#566]
I'm currently trying to implement component tests for a component that uses `vue-i18n` and I'm getting this error:

```
SyntaxError: Need to install with `app.use` function
 - /var/www/html/node_modules/@intlify/core-base/node_modules/@intlify/message-compiler/dist/message-compiler.cjs.js:58:19
 - /var/www/html/node_modules/vue-i18n/dist/vue-i18n.runtime.esm-bundler.js:105:34
 - /var/www/html/node_modules/vue-i18n/dist/vue-i18n.runtime.esm-bundler.js:2224:15
 - /components/metronic/form/Input.vue:326:1
 - /var/www/html/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:171:22
 - /var/www/html/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:7194:29
 - /var/www/html/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:7149:11
 - /var/www/html/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:5480:13
 - /var/www/html/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:5455:17
 - /var/www/html/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:5059:21
```

I have `@intlify/nuxt3` configured in my `nuxt.config.ts`:

```typescript
export default defineNuxtConfig({
    modules: ["@pinia/nuxt", "@nuxtjs/tailwindcss", "@intlify/nuxt3", "@nuxtjs/google-fonts", "@vueuse/nuxt", "nuxt-vitest"],
    intlify: {
        localeDir: "locales",
        vueI18n: {
            locale: "de",
        },
    },
// ...
```

I'm working around this problem by manually using `createI18n` in my setup file and adding it to the global plugins of vue test-utils:

```typescript
import { config } from '@vue/test-utils';
import { createI18n } from 'vue-i18n';

config.global.plugins.push(
    createI18n({
        locale: 'de',
        legacy: false,
    })
);
```

Then, since I'm also testing using `@testing-library/vue` which has another [bug](https://github.com/testing-library/vue-testing-library/issues/279), I also have to use the workaround described [there](https://github.com/testing-library/vue-testing-library/issues/279#issuecomment-1336396037) to also get the plugin working for testing-library.

I know there is nobody to blame but component tests are DX-wise very bad. I have to invest more time into getting the tests to actually work, than writing them :/

**Comment by danielroe** [comment]
Here's an example of integrating with `@nuxtjs/i18n`: https://github.com/nuxt/test-utils/tree/main/examples/i18n.

**Comment by trandaison** [comment]
@danielroe The example above is not working if change the global function `$t` by a composition function.

```diff
+ <script setup>
+ const { t: $t } = useI18n();
+ </script>
+ 
  <template>
    <div>
      Hi from @nuxtjs/i18n: {{ $t('hello') }}
    </div>
  </template>
```

I already open an issue here https://github.com/nuxt/test-utils/issues/743, please have a look when you have time.

**Comment by popadicbranislav** [comment]
is there any development regarding this issue or some solution how to get get vitest run with `@nuxtjs/i18n`? Here is a minimal reproduction for with this package - https://stackblitz.com/edit/nuxt-i18n-vitest?file=tests%2Fapp.test.ts 

As was written by others `$t` works in template, but throwing mentioned error when using `useI18n()` composable.

**Comment by ExEr7um** [comment]
> is there any development regarding this issue or some solution how to get get vitest run with `@nuxtjs/i18n`? Here is a minimal reproduction for with this package - https://stackblitz.com/edit/nuxt-i18n-vitest?file=tests%2Fapp.test.ts
> 
> As was written by others `$t` works in template, but throwing mentioned error when using `useI18n()` composable.

You can add setup file:
```ts
import { config } from '@vue/test-utils';
import { createI18n } from 'vue-i18n';

const i18n = createI18n({
  locale: 'en',
  missing: (_, key) => key,
});

config.global.plugins.push(i18n);
```

And in `vitest.config.ts`:
```ts
import { defineVitestConfig } from '@nuxt/test-utils/config'

export default defineVitestConfig({
  test: {
    environment: 'nuxt',
    setupFiles: ["tests/setup.ts"],
  },
})
```

**Comment by popadicbranislav** [comment]
Thanks, that worked for the most part. 

I had some more trouble with writing a test for pinia store where I used `useI18n()` composable. Swapping `useI18n` for `useNuxtApp().$i18n` did the job there.
