### ISSUE TITLE
regression in v0.7.0 with nuxt content

### ISSUE THREAD

**Issue by cexbrayat** [nuxt/test-utils#582]
I'm using nuxt-vitest in a project with `@nuxtjs/content` and bumping from v0.6.12 to v0.7.0 fails.

The error I see is:
```
FetchError:  (404 Cannot find any route matching /api/_content/query/ER5upk6W6J.1684485169978.json?_params=%7B%22sort%22:%5B%7B%22_path%22:-1%7D%5D,%22limit%22:2%7D. (/api/_content/query/ER5upk6W6J.1684485169978.json?_params=%7B%22sort%22:%5B%7B%22_path%22:-1%7D%5D,%22limit%22:2%7D))
 ❯ node_modules/.pnpm/@nuxt+content@2.6.0/node_modules/@nuxt/content/dist/runtime/composables/query.mjs:28:16
     26|     }
     27|   });
     28|   if (typeof data === "string" && data.startsWith("<!DOCTYPE html>")) {
       |                ^
     29|     throw new Error("Not found");
     30|   }
```

I did not manage to reproduce the exact same issue, but adding `@nuxtjs/content` to the playground does break the current test.

See https://stackblitz.com/edit/github-usaxfg?file=app.vue

This is the `playground` directory, to which I added the `@nuxtjs/content` module, and a simple markdown file in content.
The `index.vue` component uses `queryContent` to get the title of the markdown file, and displays it (works with `npm run dev`):

```vue
<template>
  <div>Index page</div>
  <div>title: {{ posts[0].title }}</div>
</template>

<script setup>
definePageMeta({
  value: 'set in index',
});
const posts = await queryContent('/').limit(1).find();
</script>
```

When running the tests with `npm run test` then you can see a lot of warnings appearing:

```
Vue warn]: Avoid app logic that relies on enumerating keys on a component instance. The keys will be empty in production mode to avoid performance overhead. 
  at <Index onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< {} > > 
  at <RouteProvider key="/" routeProps= {
  Component: [Object: Inspection interrupted prematurely. Maximum call stack size exceeded.],
  route: [Object: Inspection interrupted prematurely. Maximum call stack size exceeded.]
} pageKey="/"  ... > 
```

and the tests fail/hang (though not with the same exact error I have, but I do see the same warnings and the error I have points out to `queryContent`).

**Comment by danielroe** [comment]
The issue is coming from `@nuxt/content` which _requires_ a server to serve up the markdown. So `queryContent` is not going to work in a unit testing environment. (I'm not sure why it previously worked.)

Instead you can do something like this:

```ts
mockNuxtImport('queryContent', () => (_id: string) => ({
  limit: (_limit: number) => ({
    find: () => [{
      title: 'My page'
    }]
  })
}))
```

I've checked and this seems to work in the playground, but let me know if it doesn't work for you. (Bear in mind there are a range of unreleased changes so you may need to wait for the next release.)
