### ISSUE TITLE
Simple test super slow

### ISSUE THREAD

**Issue by andylord56** [nuxt/test-utils#589]
```
import { describe, expect, test, beforeAll } from 'vitest'
import { setup } from '@nuxt/test-utils'

describe('testing', async () => {
  await setup({})
  test('it works', () => {
    expect(true).toBe(true)
  })
})

```
![image](https://user-images.githubusercontent.com/2530510/234339022-385ce655-607a-4eb7-b707-63c8ab2aa52e.png)
65.48s is a bit slow for a simple test not sure whats causing it

**Comment by MickL** [comment]
IMHO this is still unacceptable. I wait about 15 seconds each time the tests run on a very modern hardware and this is way too long. Is there no way to reduce this to <1 second? I just want to test my server routers...
