### ISSUE TITLE
Error when running npm with nuxt-vitest added as module

### ISSUE THREAD

**Issue by Codringtoncoding** [nuxt/test-utils#602]
Hello,

I'm trying to use nuxt-vitest in order to test `NuxtImg` as when testing using `vitest` + `testing-library/vue` we are unable to use `getByRole(img)` as it just renders as a `<nuxt-image>` tag. 

I know you citied some issues with testing library but we haven't been able to run the tests due to the missing even if the module added in the `nuxt.config.ts` 

Here is the error:

 `Error while requiring module vitest-environment-nuxt/module: Error: Cannot find module`

Any help would be much appreciated

**Comment by danielroe** [comment]
The issue here was that nuxt-vitest was not compatible with vitest v0.34+. But that has been resolved in the latest nightly release of `@nuxt/test-utils` and the fix will be in the next release.

**Comment by jswhisperer** [comment]
Sorry it's an old issue but `npx nuxthub init my-app` with test-utils has the same error 
using pnpm and node 23

**Comment by danielroe** [comment]
@jswhisperer would you provide a reproduction?

**Comment by jswhisperer** [comment]
Sorry for the delay... sure

``` 
npx nuxthub init my-app
```

and select test-utils

https://stackblitz.com/edit/stackblitz-starters-soavcqnf?file=index.js

<img width="565" alt="Image" src="https://github.com/user-attachments/assets/fef1421b-3fb9-4b03-a9e1-1a76ac423a56" />

<img width="1182" alt="Image" src="https://github.com/user-attachments/assets/b3c501bb-8908-4e60-a9c3-6c4b33482937" />

<img width="1207" alt="Image" src="https://github.com/user-attachments/assets/0e8e9699-9c32-470b-aec6-e3570b830a8b" />

**Comment by jswhisperer** [comment]
@danielroe tested looks good :) thanks
