### ISSUE TITLE
Is it possible to create better error logs?

### ISSUE THREAD

**Issue by martinsjek** [nuxt/test-utils#605]
Hello.

i was just wondering is it possible to make better error logs?
Because at one moment tests just stop and all I see is:
![image](https://github.com/danielroe/nuxt-vitest/assets/36192919/3ecd7229-8304-4786-81aa-bfd3731a78f0)

**Comment by danielroe** [comment]
I think this is a little out of scope of this integration; the logging you see is coming from Vue itself.

I'd welcome any solution for this, however, I think it will probably need to be via http://github.com/vuejs/core.
