### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'app')

### ISSUE THREAD

**Issue by johanwinter1** [nuxt/test-utils#607]
in my project i get this  error when run my test

TypeError: Cannot read properties of undefined (reading 'app')
 ❯ Object.setup node_modules/vitest-environment-nuxt/dist/index.mjs:78:44
 ❯ withEnv node_modules/vitest/dist/entry.js:199:28
 ❯ run node_modules/vitest/dist/entry.js:285:3
 ❯ run node_modules/vitest/dist/worker.js:84:5
 ❯ eval node_modules/tinypool/dist/esm/worker.js:120:20

see my project on stackblitz (where the error lives)

https://stackblitz.com/edit/nuxt-starter-xbovd3

Run npm run test to see the problem.
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯

**Comment by danielroe** [comment]
The issue here was that nuxt-vitest was not compatible with vitest v0.34+. But that has been resolved in the latest nightly release of `@nuxt/test-utils` and the fix will be in the next release.
