### ISSUE TITLE
Test fails can't mount app

### ISSUE THREAD

**Issue by proggreg** [nuxt/test-utils#615]
Not sure If I've set this up wrong but I get the following error

TypeError: Cannot read properties of undefined (reading 'vueApp')

https://stackblitz.com/edit/nuxt-starter-uz1buo?file=tests%2Fapp.spec.ts

Running on windows 10 if that helps

**Comment by danielroe** [comment]
The issue here was that nuxt-vitest was not compatible with vitest v0.34+. But that has been resolved in the latest nightly release of `@nuxt/test-utils` and the fix will be in the next release.

**Comment by proggreg** [comment]
> The issue here was that nuxt-vitest was not compatible with vitest v0.34+. But that has been resolved in the latest nightly release of `@nuxt/test-utils` and the fix will be in the next release.

Thanks Daniel
