### ISSUE TITLE
trigger('click') stopped working after Nuxt update from `3.8.0` to `3.8.1`

### ISSUE THREAD

**Issue by steklopod** [nuxt/test-utils#620]
After update `"nuxt": "3.8.0"` to `3.8.1` my test started to fail:
```ts
import { describe, expect, it, vi } from 'vitest'
import { mountSuspended } from 'vitest-environment-nuxt/utils'
import type { DisplayInstance } from 'vuetify'
import * as vuetify from 'vuetify'
import GuestRegisterBtn from '~/components/main/header/GuestRegisterBtn.vue'
import * as nuxt from 'nuxt/app'

describe('Guest Register button test', () => {
  const navigateToSPY = vi.spyOn(nuxt, 'navigateTo').mockReturnValue(Promise.resolve())

  it('check login guest button for mobile in header', async () => {
    const component = await mountSuspended(GuestRegisterBtn)
    const buttonWide = component.find('button')

    // This is still working
    const classes: string[] = buttonWide.classes()
    expect(classes).contains('v-btn--variant-plain')
   // ... other working asserts

    await buttonWide.trigger('click')
    // This does not work after update 👇🏻👇🏻👇🏻👇🏻 ❌
    expect(navigateToSPY).toHaveBeenCalledOnce()
    expect(navigateToSPY).toBeCalledWith('/login?t=1') 
  })
```

**Comment by Techbinator** [comment]
I have the same issue @steklopod did you manage to find a solution?

**Comment by steklopod** [comment]
> const navigateToMock = vi.hoisted(() => vi.fn());
> mockNuxtImport('navigateTo', () => {
>   return navigateToMock;
> });

Thanks! It helped. Also worked like this:
```js
  import * as nuxt from 'nuxt/app'
  import { mockNuxtImport } from '@nuxt/test-utils/runtime'

  const navigateToSPY = vi.spyOn(nuxt, 'navigateTo').mockReturnValue(Promise.resolve())
  mockNuxtImport('navigateTo', () => navigateToSPY)
```
But your solution is shorter

**Comment by alexbruno** [comment]
Still does not work when I try to test if the button click calls a component method defined within setup:

```ts
    it('button must call loadBlogPosts', async () => {
      // Yes, the method exists, and it is listed in console.log(wrapper.vm)
      const spy = vi.spyOn(wrapper.vm, 'loadBlogPosts')

      // A button that directly CALLS the method when clicked
      await button.trigger('click')

      // This should work, but does not
      expect(spy).toHaveBeenCalled()
    })
```

**Comment by david-mears-2** [comment]
For future reference, I found that Techbinator's solution only worked for me when the click was triggered using `myComponent.vm.$emit("click")`, and not when doing a click on the html element a la `component.find("button[type='submit']").trigger("click")`.

Also (and this may be unrelated), my function wrapping the navigateTo call in the component is called submitForm, and this appeared to only be run in the test when called directly from the submit button with `@click="submitForm"`, and not when only attached to the form component itself. Outside of tests, it was sufficient to add `@submit.prevent="submitForm"` to the form component (for form components I'm using CoreUI Vue).
