### ISSUE TITLE
Unable to install main branch

### ISSUE THREAD

**Issue by henritoivar** [nuxt/test-utils#642]
### Environment

- Operating System: Windows_NT
- Node Version:     v18.11.0
- Nuxt Version:     3.8.2
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  npm@8.19.2
- Builder:          -
- User Config:      devtools, app, css, modules, runtimeConfig
- Runtime Modules:  nuxt-icon-tw@0.1.3, @nuxtjs/tailwindcss@6.10.1, @nuxtjs/i18n@8.0.0-rc.9
- Build Modules:    -

### Reproduction

 A lot of the recent fixes done seem to only work on the main branch it seems, but i'm unable to install it with npm
 
 `npm install -D "https://github.com/nuxt/test-utils.git#main"`

### Describe the bug

````
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @nuxt/test-utils@>=3.9.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
````

### Additional context

What is the recommended way to run the main branch?

**Comment by danielroe** [comment]
You can try the latest version (from `main` branch) by installing `@nuxt/test-utils-nightly` and `vitest-environment-nuxt@1.0.0-alpha.1`.

Also see https://github.com/nuxt/test-utils/issues/644.
