### ISSUE TITLE
After upgrading to new version imports mocks broke

### ISSUE THREAD

**Issue by amacatoe** [nuxt/test-utils#658]
### Environment

Nuxt project info:                                                                                  

------------------------------
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.8.2
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  npm@9.4.2
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-ctgbhq?file=src%2Ftests%2Findex.test.ts

### Describe the bug

Hi! After migration from nuxt-vitest to this repo, we founded that all imports mocks were broken. 
We used this [example](https://github.com/danielroe/nuxt-vitest#mocknuxtimport) and it worked perfectly in nuxt-vitest and previous versions. 

The problem is that the mock works correctly inside the test, but it doesn't seem to apply inside the function. useRoute().params is defined inside the test, but in function - undefined. 

```
test('get params', () => {
    expect(useFoo()).toBeFalsy(); //correct
    const params = {
      id: '11312424',
    };
    useRouteMock.mockImplementation(() => {
      return { query: {}, path: '/', params };
    });

    //here useRoute().params - object (!) 

    expect(useFoo()).not.toBeFalsy(); //here useRoute().params - undefined and result for test - false 
  });
```

**Comment by danielroe** [comment]
This seems to be working fine with the latest version:

https://stackblitz.com/edit/nuxt-starter-ufbgam?file=package.json,src/tests/index.test.ts
