### ISSUE TITLE
Nuxt instance is unavailable after v3.9.0 upgrade

### ISSUE THREAD

**Issue by jg-jgriffith** [nuxt/test-utils#665]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.17.0`
- Nuxt Version:     `3.8.2`
- CLI Version:      `3.10.0`
- Nitro Version:    `2.8.1`
- Package Manager:  `pnpm@8.12.1`
- Builder:          `-`
- User Config:      `typescript`, `ssr`, `experimental`, `devtools`, `$development`, `build`, `runtimeConfig`, `alias`, `vite`, `modules`, `image`, `googleFonts`, `primevue`
- Runtime Modules:  `@nuxt/devtools@1.0.6`, `@nuxt/image@1.1.0`, `@nuxtjs/google-fonts@3.1.3`, `@nuxtjs/tailwindcss@6.10.1`, `@pinia/nuxt@0.5.1`, `nuxt-icon@0.5.0`, `nuxt-primevue@0.2.0`, `@nuxt/test-utils/module@3.9.0`
- Build Modules:    `-`

### Reproduction

described in context

### Describe the bug

After upgrading to v3.9.0 and following the upgrade guide from `nuxt-vitest` a basic test no longer works.

I do have nuxt image installed and found the seemingly-related issue in the repo, but applying the workaround did not result in any change.

### Additional context

`vitest.config.mts`:
```
import { defineVitestConfig } from '@nuxt/test-utils/config'

export default defineVitestConfig({
  test: {
    globals: true,
    environment: 'nuxt',
    reporters: ['html'],
    include: ['tests/**/*.test.ts'],
    coverage: {
      provider: 'v8',
      include: ['src/**'],
    },
  },
})
```

Only test file:

```
import { describe, it, expect } from 'vitest'
import { mountSuspended } from '@nuxt/test-utils/runtime'
import FormControl from '../components/FormControl.vue'

describe('FormControl', () => {
  it('renders an FormControl', async () => {
    const component = await mountSuspended(FormControl, {
      props: {
        label: 'Label',
        placeholder: 'Placeholder',
        modelValue: 'value',
      },
    })
    expect(component).toBeDefined()
  })
})
```

### Logs

```shell-script
vitest run --config vitest.config.mts --coverage


🌼   daisyUI 4.4.20
├─ ✔︎ 1 theme added		https://daisyui.com/docs/themes
╰─ ❤︎ Support daisyUI project:	https://opencollective.com/daisyui

file:///Users/Me/Projects/example/frontend/node_modules/.pnpm/@nuxt+kit@3.8.2/node_modules/@nuxt/kit/dist/index.mjs:32
    throw new Error("Nuxt instance is unavailable!");
          ^

Error: Nuxt instance is unavailable!
    at useNuxt (file:///Users/Me/Projects/example/portal2-frontend/node_modules/.pnpm/@nuxt+kit@3.8.2/node_modules/@nuxt/kit/dist/index.mjs:32:11)
    at installNuxtModule (file:///Users/Me/Projects/example/portal2-frontend/node_modules/.pnpm/nuxt@3.8.2_@types+node@18.19.3_eslint@8.56.0_typescript@5.3.3_vite@5.0.10/node_modules/nuxt/dist/chunks/features.mjs:41:16)
    at file:///Users/Me/Projects/example/frontend/node_modules/.pnpm/nuxt@3.8.2_@types+node@18.19.3_eslint@8.56.0_typescript@5.3.3_vite@5.0.10/node_modules/nuxt/dist/index.mjs:1290:77

Node.js v18.17.0
 ELIFECYCLE  Test failed. See above for more details.
```

**Comment by danielroe** [comment]
This issue is a bug in Nuxt and has been resolved in https://github.com/nuxt/nuxt/pull/24605 and will be included in the next release of Nuxt: v3.9.0.
