### ISSUE TITLE
mockNuxtImport not working in page components when mounting app with mountSuspended

### ISSUE THREAD

**Issue by mcrapts** [nuxt/test-utils#666]
### Environment

```
------------------------------
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.8.2
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  npm@9.4.2
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------
```

### Reproduction

https://stackblitz.com/edit/github-refqkp?file=test%2Fapp.nuxt.spec.ts

### Describe the bug

1. Run `vitest` in the reproduction link.
2. Observe the HTML of the `app.vue` in the test is rendered as `<div>mock return value</div>`.
3. Observe the HTML of `app2.vue` in the test is rendered as `<div>actual value</div>`.
4. Observe the HTML of the `pages/index.vue` in the test is rendered as `<div>actual value</div>`.

My expectation is that the useAsyncData mock works with page components. `app.vue` is usually just a container component and doesn't do data fetching, that usually happens in the page component.

The above scenarios worked with `nuxt-vitest`.

**Comment by danielroe** [comment]
This is prone to happen if `vitest` has already processed the SFC before it processes the mock statement.

Maybe we can invalidate the module manually, or prevent it from processing routes (which is likely the issue).

**Comment by mcrapts** [comment]
Is there a workaround in the mean time I can use to mock useAsyncData? My goal is to mount app.vue with one or more routes and then test if everything renders according to expectations

**Comment by mcrapts** [comment]
I updated `@nuxt/test-utils` to 3.11.0 and also made sure `vitest` and `vitest-environment-nuxt` were updated to their latest versions, and now this issue is resolved for me. So issue can be closed.
