### ISSUE TITLE
Error running test after upgrade to 3.9.0

### ISSUE THREAD

**Issue by bsimakis** [nuxt/test-utils#679]
### Environment

- Operating System: `Darwin`
- Node Version:     `v21.5.0`
- Nuxt Version:     `3.9.0`
- CLI Version:      `3.10.0`
- Nitro Version:    `2.8.1`
- Package Manager:  `npm@10.2.4`
- Builder:          `-`
- User Config:      `alias`, `app`, `devtools`, `eslint`, `i18n`, `imports`, `modules`, `nitro`, `runtimeConfig`, `ssr`, `testUtils`, `typescript`, `vite`, `vuetify`
- Runtime Modules:  `@pinia-plugin-persistedstate/nuxt@1.2.0`, `@pinia/nuxt@0.5.1`, `@nuxtjs/i18n@8.0.0`, `@nuxtjs/eslint-module@4.1.0`, `nuxt-typed-router@3.5.0`, `@nuxt/test-utils/module@3.9.0`, `vuetify-nuxt-module@0.7.3`, `nuxt-lodash@2.5.3`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-cyqbu8

### Describe the bug

After upgrading to 3.9.0, I am getting errors when running tests due to missing identifiers in the nuxt package. Reproduction shows error from my middleware test but I get similar errors when running component tests but this time the error is "Error: Missing "#build/paths.mjs" specifier in "nuxt" package"

**Comment by danielroe** [comment]
The issue here seems to be that you are adding additional paths/alias configuration. It works with the following changes:

```diff
- import { resolve } from 'path';
  import { defineVitestConfig } from '@nuxt/test-utils/config';
- import tsconfigPaths from 'vite-tsconfig-paths';
  
  export default defineVitestConfig({
-    plugins: [tsconfigPaths()],
    test: {
-      alias: {
-        '@components/*': new URL('./', import.meta.url).pathname,
-      },
      dir: './tests/unit',
      environment: 'happy-dom',
      coverage: {
        provider: 'istanbul', // or 'v8'
        reporter: ['text', 'json', 'html'],
        reportsDirectory: './test-results/',
      },
    },
-    resolve: {
-      alias: [{ find: '@', replacement: resolve(__dirname, '.') }],
-    },
  });
```

Instead, why not set those aliases in your Nuxt config or via overrides, like this?

```ts
import { resolve } from 'path';
import { defineVitestConfig } from '@nuxt/test-utils/config';
import tsconfigPaths from 'vite-tsconfig-paths';

export default defineVitestConfig({
  test: {
    environmentOptions: {
      nuxt: {
        overrides: {
          alias: {
            // here
          }
        }
      }
    },
});
```
