### ISSUE TITLE
RouterLink not using correct href

### ISSUE THREAD

**Issue by StevenPewsey** [nuxt/test-utils#686]
### Environment

```
------------------------------
- Operating System: Darwin
- Node Version:     v18.16.1
- Nuxt Version:     3.8.2
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  yarn@3.6.0
- Builder:          -
- User Config:      app, css, build, devServer, modules, runtimeConfig, nitro, vite, i18n, hooks
- Runtime Modules:  @nuxtjs/tailwindcss@6.10.1, @pinia/nuxt@0.4.11, @pinia-plugin-persistedstate/nuxt@1.2.0, @thrivadev/thrive/nuxt@2.1.1, @vueuse/nuxt@10.7.0, @nuxtjs/i18n@8.0.0-rc.9, @vee-validate/nuxt@4.12.2
- Build Modules:    -
------------------------------
```

### Reproduction

https://stackblitz.com/edit/github-tqbkqz

### Describe the bug

The mocked `RouterLink` [component](https://github.com/nuxt/test-utils/blob/main/src/runtime-utils/components/RouterLink.ts) is passing `props.to` directly as the href, however this results in the href being an object when `to` is an object (e.g. if passing through `path` and `state`).

This causes tests to fail even though the links work fine in the browser

```
- http://localhost:3000/thelink
+ http://localhost:3000/[object%20Object]
```

**Comment by manniL** [comment]
Indeed! PR welcome to address that issue so the whole path is passed if `props.to` is no string but a route object 👍🏻
