### ISSUE TITLE
Support E2E tests within Cucumber ecosystem

### ISSUE THREAD

**Issue by antoinezanardi** [nuxt/test-utils#697]
## 🚀 Why This Feature?

Nuxt Test Utils provides a variety of tools for conducting End-to-End (E2E) tests with `playwright` and a chosen test runner (currently `vitest` or `jest`). While this is a valuable capability, I believe it could be enhanced further by integrating support for Cucumber.

Here's the challenge: to initiate a Nuxt server for E2E tests, you typically invoke the `setup()` method from the `test-utils/e2e` Nuxt package, as documented [here](https://nuxt.com/docs/getting-started/testing#setup-1). In essence, this function determines your test runner and associates specific actions with different hooks (e.g., starting the server in `beforeAll`, closing the connection in `afterAll`, etc.).

The issue is that using this method outside of a test runner ecosystem (`jest` or `vitest`) is problematic because it cannot locate the necessary hooks to attach the functions to.

## 🧠 How to Implement It?

I propose exposing the various functions called by `setup()` and manually invoking them in the framework of your choice, such as Cucumber. For instance, you could do something like this in TypeScript:

```typescript
// This is the Before hook of Cucumber
Before(async function(this: CustomWorld): Promise<void> {
  // Create a Playwright Test Context with desired options
  const context = createTestContext({});
  await startServer(context);
  
  // Use the Playwright API in Cucumber step definitions
  this.page = await createPage("/");
});
```

I'm unsure if this is already achievable. Regardless, I haven't come across any relevant implementations of `nuxt3` + `playwright` + `cucumber`.

## 🔍 Reproduction Repository

You can test my setup in my [repository](https://github.com/antoinezanardi/werewolves-assistant-web-next/tree/develop) by running the `npm run test:cucumber` command.

I'd be delighted to assist in building this feature. If it's already possible or implemented differently, I'd appreciate the opportunity to document it in the Nuxt documentation.

### Additional information

- [x] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
I think this should already be possible!

Currently `setup` is very simple:

```ts
export async function setup (options: Partial<TestOptions> = {}) {
  const hooks = createTest(options)

  const setupFn = setupMaps[hooks.ctx.options.runner]

  await setupFn(hooks)
}
```

The 'setupFn' might look a bit like this:

```ts
export default async function setupJest (hooks: TestHooks) {
  const { jest, test, beforeEach, afterAll, afterEach } = await import('@jest/globals')

  hooks.ctx.mockFn = jest.fn

  test('setup', hooks.setup, hooks.ctx.options.setupTimeout)
  beforeEach(hooks.beforeEach)
  afterEach(hooks.afterEach)
  afterAll(hooks.afterAll)
}
```

So all you need to do is the equivalent for cucumber. Use `createTest` to get the hooks + other context.

**Comment by antoinezanardi** [comment]
After some tries, here is the version I ended with :
```typescript
// hooks.ts
import { After, AfterAll, Before } from "@cucumber/cucumber";
import { createPage, createTest } from "@nuxt/test-utils/e2e";

import type { CustomWorld } from "~/tests/acceptance/shared/types/word.types";

const { afterEach, afterAll, setup } = createTest({ runner: "vitest", server: true });

Before({ timeout: 60 * 10000 }, async function(this: CustomWorld): Promise<void> {
  console.log("before setup"); // <- This log prints
  await setup();
  console.log("setup"); // <- This log doesn't
  this.page = await createPage("/");
});

After((): void => {
  afterEach();
});

AfterAll((): void => {
  afterAll();
});
```

Unfortunately, the `setup` command is exiting in error…  Here are the logs :

```shell
> cross-env NODE_OPTIONS='--loader ts-node/esm' NODE_ENV=test cucumber-js --config config/cucumber/cucumber.json -b

(node:36320) ExperimentalWarning: `--experimental-loader` may be removed in the future; instead use `register()`:
--import 'data:text/javascript,import { register } from "node:module"; import { pathToFileURL } from "node:url"; register("ts-node/esm", pathToFileURL("./"));'

(Use `node --trace-warnings ...` to show where the warning was created)
before setup

Listening on http://127.0.0.1:51418

[Vue Router warn]: No match found for location with path "/roles"

1 scenario (1 failed)
1 step (1 failed)
0m12.118s (executing steps: 0m12.112s)
 ELIFECYCLE  Command failed with exit code 1.
```

I don't think the warn is the cause here, my app is working perfectly fine in development and production. Do I miss something in the hooks ? 

As always, you can test my setup in my [repository](https://github.com/antoinezanardi/werewolves-assistant-web-next/tree/main) by running the `npm run test:cucumber` command.

**Comment by danielroe** [comment]
I tried testing your setup but got this error:

```
❯ npm run test:cucumber

> werewolves-assistant-web-next@1.1.1 test:cucumber
> cross-env NODE_OPTIONS='--loader ts-node/esm' NODE_ENV=test cucumber-js --config config/cucumber/cucumber.json

(node:96317) ExperimentalWarning: `--experimental-loader` may be removed in the future; instead use `register()`:
--import 'data:text/javascript,import { register } from "node:module"; import { pathToFileURL } from "node:url"; register("ts-node/esm", pathToFileURL("./"));'
(Use `node --trace-warnings ...` to show where the warning was created)
1) Scenario: 🏠 Home Page is displayed # tests/acceptance/features/home/features/home.feature:5
   ✖ Before # file:/private/tmp/werewolves-assistant-web-next/tests/acceptance/features/support/hooks.ts:3
       Error: Cannot find package 'async_hooks' imported from /private/tmp/werewolves-assistant-web-next/node_modules/.pnpm/p-limit@5.0.0/node_modules/p-limit/package.json
```

Am I missing a setup step?

**Comment by antoinezanardi** [comment]
I'm sorry, I forgot to mention to checkout to the `feat/cucumber-setup` branch before …!

The updated setup is on it.

**Comment by danielroe** [comment]
I gotchu

![CleanShot 2024-01-17 at 13 11 05@2x](https://github.com/nuxt/test-utils/assets/28706372/fac8e690-ed55-4aba-9fcd-20fe384ec728)

**Comment by antoinezanardi** [comment]
Thank you for your help ! Can't wait to test it 🥳

**Comment by danielroe** [comment]
you are very welcome ❤️

**Comment by antoinezanardi** [comment]
If you want, I implemented plenty of real-life cucumber scenarios using playwright and nuxt based on this present PR. 

You can check them [here](https://github.com/antoinezanardi/werewolves-assistant-web-next) under the `tests/acceptance` directory.

**Comment by danielroe** [comment]
You can pass `dev: true` to use a dev server. It doesn't currently 'share' the running dev server if you have one separately but this is absolutely on my list.
