### ISSUE TITLE
`renderSuspended` does not provide the values returned from `setup` to the template

### ISSUE THREAD

**Issue by obulat** [nuxt/test-utils#722]
### Environment

Nuxt project info:                                                                                      

------------------------------
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.9.3
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      devtools, modules
- Runtime Modules:  @nuxt/test-utils/module@3.10.0
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-7wbhms?file=test%2Ftest-component.spec.ts

### Describe the bug

`renderSuspended` does not pass the values from `setup` function (not the `<script setup>`) to the `template`. The `mountSuspended` works fine.

### Additional context

In the Openverse Nuxt 3 migration PR, I replaced `render(renderContext, ...args)` with `render(_ctx, ...args)` on this line:

https://github.com/nuxt/test-utils/blob/bc86d23b2cf92aa3c3f19d52944452e4e5c27d63/src/runtime-utils/render.ts#L113

which seems to fix the issue.

**Comment by joaovitoras** [comment]
This is because of defineComponent wrapper
I opened a PR to fix this https://github.com/nuxt/test-utils/issues/722
