### ISSUE TITLE
Server utils composable is not defined in test

### ISSUE THREAD

**Issue by PoloLacoste** [nuxt/test-utils#732]
### Environment

- Operating System: Windows_NT
- Node Version:     v21.6.0
- Nuxt Version:     3.9.3
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  pnpm@8.14.3
- Builder:          -
- User Config:      modules, devtools
- Runtime Modules:  @nuxt/test-utils/module@3.10.0
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-7fr8te?file=test%2Fapp.test.ts

### Describe the bug

In`server/domain` I created a `TestService` class which is importing a composable from `server/utils`.

`server/utils/test.ts` :
```ts
export const useTest = () => {
  return 1
}
```

`server/domain/test-service.ts` :
```ts
export class TestService {
  private test = useTest()
}
```

When I initialize the `TestService` class inside an api endpoint it works, but when I try to initialize the same class inside a test this error appears `ReferenceError: useTest is not defined`.

`test/app.test.ts` :
```ts
// @vitest-environment nuxt
import { expect, test } from 'vitest';
import { TestService } from '~/server/domain/test-service';

test('my test', () => {
  const service = new TestService();
  expect(service).toBeDefined();
});
```

**Comment by danielroe** [comment]
Nitro server environment is not yet supported - the environment provided is a _client-side_ runtime vitest environment.

You can track this feature in https://github.com/nuxt/test-utils/issues/531.
