### ISSUE TITLE
Missing "main" in package.json

### ISSUE THREAD

**Issue by jacktan165** [nuxt/test-utils#742]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v16.18.1
- Nuxt Version:     2.15.8
- CLI Version:      3.10.0
- Nitro Version:    -
- Package Manager:  yarn@1.22.19
- Builder:          webpack
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

import this package from another package, and it will complain it cannot find it.

### Describe the bug

It is missing the "main" key in package.json, hence I get `Cannot find module '@nuxt/test-utils'` error.

**Comment by danielroe** [comment]
This package is not usable in Nuxt 2 and it is ESM-only so it does not have a `main` entry.
