### ISSUE TITLE
Experimental optimizeDeps.disabled vite 5.1

### ISSUE THREAD

**Issue by productdevbook** [nuxt/test-utils#754]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.10.1
- CLI Version:      3.10.0
- Nitro Version:    -
- Package Manager:  pnpm@8.14.0
- Builder:          -
- User Config:      devtools, modules, pergel
- Runtime Modules:  pergel/nuxt
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-66e6cf?file=tests%2Fmy-file.nuxt.test.ts

### Describe the bug

```ts
[warn] (!) Experimental optimizeDeps.disabled and deps pre-bundling during build were removed in Vite 5.1.
    To disable the deps optimizer, set optimizeDeps.noDiscovery to true and optimizeDeps.include as undefined or empty.
    Please remove optimizeDeps.disabled from your config.
```

**Comment by danielroe** [comment]
This is an upstream issue in vitest - raised https://github.com/vitest-dev/vitest/issues/5211.
