### ISSUE TITLE
error.vue can't be tested

### ISSUE THREAD

**Issue by martinsjek** [nuxt/test-utils#769]
### Environment

StackBlitz

### Reproduction

https://stackblitz.com/edit/github-vy6psx-sn3lfr?file=.nuxtignore,error.vue,__tests__%2Ferror.spec.ts

### Describe the bug

I get this error:
`
[Vue Router warn]: No match found for location with path "/123"
[Vue warn]: Cannot mutate <script setup> binding "error" from Options API. 
  at <MountSuspendedComponent error= {
  url: '/123',
  statusCode: 404,
  statusMessage: 'Not Found',
  message: 'Error',
  description: ''
} > 
  at <MountSuspendedHelper> 
  at <Anonymous ref="VTU_COMPONENT" > 
  at <VTUROOT>
[Vue warn]: Unhandled error during execution of render function 
  at <MountSuspendedComponent error= {
  url: '/123',
  statusCode: 404,
  statusMessage: 'Not Found',
  message: 'Error',
  description: ''
} > 
  at <MountSuspendedHelper> 
  at <Anonymous ref="VTU_COMPONENT" > 
  at <VTUROOT>
`

### Additional context

You can get this error running: npm run test ./__tests__/error.spec.ts

**Comment by vhovorun** [comment]
Same issue, reproduces when you have `useError`  composable inside of your component, without it test passes

**Comment by DariaYeremina** [comment]
Got the same error trying to test overwritten `ProseImg` component

**Comment by strokirk** [comment]
Same as https://github.com/nuxt/test-utils/issues/684 ?

**Comment by IT-WIBRC** [comment]
> ### Environment
> 
> StackBlitz
> ### Reproduction
> 
> https://stackblitz.com/edit/github-vy6psx-sn3lfr?file=.nuxtignore,error.vue,__tests__%2Ferror.spec.ts
> ### Describe the bug
> 
> I get this error: `[Vue Router warn]: No match found for location with path "/123" [Vue warn]: Cannot mutate <script setup> binding "error" from Options API. at <MountSuspendedComponent error= { url: '/123', statusCode: 404, statusMessage: 'Not Found', message: 'Error', description: '' } > at <MountSuspendedHelper> at <Anonymous ref="VTU_COMPONENT" > at <VTUROOT> [Vue warn]: Unhandled error during execution of render function at <MountSuspendedComponent error= { url: '/123', statusCode: 404, statusMessage: 'Not Found', message: 'Error', description: '' } > at <MountSuspendedHelper> at <Anonymous ref="VTU_COMPONENT" > at <VTUROOT>`
> ### Additional context
> 
> You can get this error running: npm run test ./**tests**/error.spec.ts
> ### Logs
> 
> _No response_

I got the same error with a props name `error` in my component when I tested using `mountSuspended` from `@nuxt/test-utils/runtime`. To resolve it, I have just changed it to `errorMessage`. Maybe the test engine has a constraint with the name `error` . 

I suggest changing the name `error` to a context name like `404.vue`.

**Comment by danielroe** [comment]
This should now be resolved in https://github.com/nuxt/test-utils/pull/1025.
