### ISSUE TITLE
Failed to load url #imports after importing mockNuxtImport

### ISSUE THREAD

**Issue by chronicadventure** [nuxt/test-utils#800]
### Environment

- Operating System: Windows_NT
- Node Version:     v18.19.0
- Nuxt Version:     3.11.1
- CLI Version:      3.11.1
- Nitro Version:    2.9.4
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      devtools, modules
- Runtime Modules:  @nuxt/test-utils/module

### Reproduction

https://github.com/chronicadventure/nuxt-bug

just run `npm test` and the console will error out. *Note* you don't even need an actual test, just the import causes the entire file to fail.

### Describe the bug

Importing `import { mockNuxtImport } from '@nuxt/test-utils/runtime'` as stated in the docs causes the entire test file to fail.

### Logs

```shell-script
DEV  v1.4.0 C:/Users/AdrianCampos/BugRepo/repro

 ❯ tests/random.nuxt.test.js (0)

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Failed Suites 1 ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯

 FAIL  tests/random.nuxt.test.js [ tests/random.nuxt.test.js ]
Error: Failed to load url #imports (resolved id: #imports) in C:/Users/AdrianCampos/BugRepo/node_modules/@nuxt/test-utils/dist/runtime-utils/index.mjs. Does the file exist?
 ❯ loadAndTransform ../node_modules/vite/dist/node/chunks/dep-B-u6xNiR.js:53832:21

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[1/1]⎯

 Test Files  1 failed (1)
      Tests  no tests
   Start at  21:58:52
   Duration  2.22s (transform 69ms, setup 0ms, collect 0ms, tests 0ms, environment 0ms, prepare 846ms)


 FAIL  Tests failed. Watching for file changes...
       press h to show help, press q to quit
```

**Comment by danielroe** [comment]
In order to use the imports from `@nuxt/test-utils/runtime`, you need to configure vitest to run in a Nuxt runtime environment, which you can do by following the steps here: https://nuxt.com/docs/getting-started/testing#setup

**Comment by larsalbrecht** [comment]
> In order to use the imports from `@nuxt/test-utils/runtime`, you need to configure vitest to run in a Nuxt runtime environment, which you can do by following the steps here: https://nuxt.com/docs/getting-started/testing#setup

If i use // @vitest-environment nuxt in my test file, I get this error:

> WARN - IDE integration: Cannot finish not started testing
>
>TypeError: Cannot read properties of undefined (reading 'app')
    at Object.setup (/frontend/node_modules/@nuxt/test-utils/dist/vitest-environment.mjs:68:87)
    at withEnv (/frontend/node_modules/vitest/dist/chunks/runtime-runBaseTests.SKlFOhuq.js:80:33)
    at run (/frontend/node_modules/vitest/dist/chunks/runtime-runBaseTests.SKlFOhuq.js:103:9)
    at runBaseTests (/frontend/node_modules/vitest/dist/vendor/base.nhvUBzQY.js:30:3)
    at run (/frontend/node_modules/vitest/dist/worker.js:130:5)
    at /frontend/node_modules/tinypool/dist/esm/entry/worker.js:72:20

**Comment by spider-hand** [comment]
Same thing happens to me.

I also failed to import it and found this thread and tried to run the test with `nuxt` environment, then this error happened.

> TypeError: Cannot read properties of undefined (reading 'app')
 Object.setup node_modules/@nuxt/test-utils/dist/vitest-environment.mjs:68:87
 withEnv node_modules/vitest/dist/chunks/runtime-runBaseTests.-x-nNuJ_.js:81:33
 run node_modules/vitest/dist/chunks/runtime-runBaseTests.-x-nNuJ_.js:105:9
 runBaseTests node_modules/vitest/dist/vendor/base.gAwDs8Jc.js:30:3
 run node_modules/vitest/dist/worker.js:93:5
 node_modules/tinypool/dist/esm/entry/worker.js:72:20

The versions of the dependencies are below.

- "nuxt": "^3.11.2",
- "@nuxt/test-utils": "^3.12.1",
- "@vue/test-utils": "^2.4.5",
- "jsdom": "^24.0.0",
- "playwright-core": "^1.43.1",
- "vitest": "^1.5.2"

`nuxt.config.ts`

```
export default defineNuxtConfig({
  ...
  modules: [
    ...
    "@nuxt/test-utils/module",
    ...
  ],
  ...
```

`vitest.config.ts`

```ts
import { defineConfig } from "vite";
import vue from "@vitejs/plugin-vue";
import { fileURLToPath } from "url";

export default defineConfig({
  plugins: [vue()],
  test: {
    globals: true,
    environment: "nuxt",
  },
  resolve: {
    alias: [
      {
        find: "@",
        replacement: fileURLToPath(new URL("./", import.meta.url)),
      },
    ],
  },
});
```

**Comment by danielroe** [comment]
Please follow the instructions to use the config definition helper from this module in your vitest config, or you will not be benefiting from this library.
