### ISSUE TITLE
failed to load config from vitest.config.ts, ReferenceError: structuredClone is not defined

### ISSUE THREAD

**Issue by MellowCo** [nuxt/test-utils#810]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v16.14.2
- Nuxt Version:     3.11.1
- CLI Version:      3.11.1
- Nitro Version:    2.9.5
- Package Manager:  npm@9.7.1
- Builder:          -
- User Config:      devtools, css, modules
- Runtime Modules:  @nuxtjs/tailwindcss@6.11.4, @nuxt/test-utils/module@3.12.0
- Build Modules:    -
------------------------------

### Reproduction

https://github.com/Ayamarmash/Nuxt

### Describe the bug

run test

![image](https://github.com/nuxt/test-utils/assets/47939250/174840c3-c8cb-46fa-8653-acd4f8bd2db0)

**Comment by max-zinn** [comment]
What was the solution? I'm having the same issue right now.

**Comment by rzschoch** [comment]
I have the same problem, is there a solution?

**Comment by TheAlexLichter** [comment]
Updating the Node version (in case of the author here). LTS is reocmmended [but > 17](https://developer.mozilla.org/en-US/docs/Web/API/Window/structuredClone#browser_compatibility) is necessary.
