### ISSUE TITLE
vitest does not resolve nitro (h3) auto-imports

### ISSUE THREAD

**Issue by pmwmedia** [nuxt/test-utils#827]
### Environment

- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.11.2
- CLI Version:      3.11.1
- Nitro Version:    2.9.6
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-xdspn8

### Describe the bug

It is impossible to test server API and server route implementations directly, because vitest does not auto import nitro (h3) functions like e.g. `defineEventHandler()`.

When executing the test in the linked minimal reproduction, I receive this error:

```
FAIL  test/server/routes/something.spec.ts [ test/server/routes/something.spec.ts ]
ReferenceError: defineEventHandler is not defined
 ❯ eval server/routes/something.ts:1:217
 ❯ eval test/server/routes/something.spec.ts:2:31
```

### Additional context

server/routes/something.ts
```typescript
export default defineEventHandler(() => 'OK');
```

test/routes/something.spec.ts
```typescript
import { it } from 'vitest';
import handler from '../../../server/routes/something';

it('should return OK', () => {
  const response = handler({} as any);
  expect(response).toBe('OK');
});

```

**Comment by danielroe** [comment]
Yes, the vitest environment is a _client_ environment.

We can track nitro environment via https://github.com/nuxt/test-utils/issues/531.

**Comment by dev-nakaya** [comment]
Getting comments
