### ISSUE TITLE
Plugins not overwritten when passed as options

### ISSUE THREAD

**Issue by lucasecdb** [nuxt/test-utils#828]
### Environment

- Operating System: `Darwin`
- Node Version:     `v20.11.0`
- Nuxt Version:     `3.11.2`
- CLI Version:      `3.11.1`
- Nitro Version:    `2.9.6`
- Package Manager:  `pnpm@8.14.2`
- Builder:          `-`
- User Config:      `devtools`, `modules`, `pinia`, `typescript`
- Runtime Modules:  `@nuxt/test-utils/module@3.12.1`, `@pinia/nuxt@0.5.1`
- Build Modules:    `-`

### Reproduction

https://github.com/lucasecdb/nuxt-app-pinia-repro

Install dependencies with `pnpm install` then run `pnpm test`

### Describe the bug

If you configure a vue plugin using Nuxt plugins, like the following:

```ts
// plugins/pinia.ts
import { createPinia } from 'pinia';

export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.vueApp.use(createPinia())
})
```

Given the following component and Pinia store:

```vue
<template>
  <p>{{ date }}</p>
</template>

<script setup>
const store = useMyStore();

const date = computed(() => store.date);
</script>
```

```ts
// stores/my-store.ts
export const useMyStore = defineStore('my-store', () => {
  return {
    date: ref(new Date()),
  };
});
```

And then try to overwrite that plugin during testing:

```ts
// __tests__/my-component.test.ts
import { createPinia } from 'pinia';

it('should pass', async () => {
  await renderSuspended(MyComponent, {
    global: { plugins: [createPinia()] },
  });

  // ...
});
```

The instance returned by `useMyStore` will always use the Pinia store supplied by `plugins/pinia`, and not from the `global.plugins` parameter provided to `renderSuspended`.

**Comment by lucasecdb** [comment]
The issue occurs because on `@vue/test-utils` the `plugins` from the global properties are applied _before_ the `provides`:

 - Plugins are applied on line 276: https://github.com/vuejs/test-utils/blob/1cdd7ae5a973e8a2de8eef8c22159bc0cc97f911/src/createInstance.ts#L269-L278
 - Provides values are copied to the vue instance on line 303: https://github.com/vuejs/test-utils/blob/1cdd7ae5a973e8a2de8eef8c22159bc0cc97f911/src/createInstance.ts#L299-L305

And since `renderSuspended` copies over the provided values from the global instance down to the `render` call, the plugin will always be overwritten back by the `vueApp` provided value:

https://github.com/nuxt/test-utils/blob/08ee35155579889e6c41f8abe9340d0e5f803111/src/runtime-utils/render.ts#L136

**Comment by danielroe** [comment]
This is now resolved in the latest `@vue/test-utils`: https://github.com/vuejs/test-utils/releases/tag/v2.4.6.
