### ISSUE TITLE
Error updating to Vitest 2

### ISSUE THREAD

**Issue by alditis** [nuxt/test-utils#892]
### Describe the feature

Vitest current version is 2.0.3.
@nuxt/test-utils uses Vitest 1.0.6.

Error:
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: @nuxt/test-utils@3.13.1
npm ERR! Found: vitest@2.0.3
npm ERR! node_modules/vitest
npm ERR!   dev vitest@"2.0.3" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peerOptional vitest@"^0.34.6 || ^1.0.0" from @nuxt/test-utils@3.13.1
npm ERR! node_modules/@nuxt/test-utils
npm ERR!   dev @nuxt/test-utils@"3.13.1" from the root project
npm ERR!   @nuxt/test-utils@">=3.9.0" from vitest-environment-nuxt@1.0.0
npm ERR!   node_modules/vitest-environment-nuxt
npm ERR!     vitest-environment-nuxt@"^1.0.0" from @nuxt/test-utils@3.13.1
npm ERR! 
npm ERR! Conflicting peer dependency: vitest@1.6.0
npm ERR! node_modules/vitest
npm ERR!   peerOptional vitest@"^0.34.6 || ^1.0.0" from @nuxt/test-utils@3.13.1
npm ERR!   node_modules/@nuxt/test-utils
npm ERR!     dev @nuxt/test-utils@"3.13.1" from the root project
npm ERR!     @nuxt/test-utils@">=3.9.0" from vitest-environment-nuxt@1.0.0
npm ERR!     node_modules/vitest-environment-nuxt
npm ERR!       vitest-environment-nuxt@"^1.0.0" from @nuxt/test-utils@3.13.1
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by aethr** [comment]
The advice here from @dosubot doesn't work.

This conflict was resolved in https://github.com/nuxt/test-utils/pull/888 last week, so it should be fixed in the next release.

Unfortunately nuxt/test-utils hasn't had a new release for a couple of months, hopefully the maintainer will find time to prep a release to get this fix out. :crossed_fingers:

**Comment by Gugustinette** [comment]
The fact that there's no release makes it kinda impossible to upgrade to Vitest 2. 😕

Also @danielroe I think the CI has a problem ? I wanted to use a nightly release (afaik they're created automatically when pushing to main) but can't find any.
I looked at the Github Action and it seems like an error is throwing during nightly release : https://github.com/nuxt/test-utils/actions/runs/9997183613/job/27633175272#step:7:11

**Comment by danielroe** [comment]
Indeed, hopefully the maintainer will find time to prep a release.

**Comment by danielroe** [comment]
(Who can say ...?)

**Comment by Gugustinette** [comment]
<img width="768" alt="Capture d’écran 2024-07-26 à 21 50 06" src="https://github.com/user-attachments/assets/2b9d6391-b42f-4453-86ef-99d54c646852">

Feels good

**Comment by danielroe** [comment]
released ✅

**Comment by Gugustinette** [comment]
Works like a charm, thanks for handling this so fast !

**Comment by aethr** [comment]
Thanks @danielroe ! :heart: 

Did not mean any disrespect, I genuinely appreciate the work and time you put into this.

**Comment by danielroe** [comment]
No disrespect received ❤️
