### ISSUE TITLE
useFakeTimers isn't working for the setInterval.

### ISSUE THREAD

**Issue by gsamal** [nuxt/test-utils#897]
### Environment

```
System:
    OS: Linux 5.15 Ubuntu 20.04.6 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz
    Memory: 7.71 GB / 15.38 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 20.11.1 - ~/.nvm/versions/node/v20.11.1/bin/node
    npm: 10.2.4 - ~/.nvm/versions/node/v20.11.1/bin/npm
  Browsers:
    Chrome: 112.0.5615.49
  npmPackages:
    vitest: 1.6.0 => 1.6.0

```

### Reproduction

Non-working code with setInterval -
```
  describe('Testing timers', () => {
    let triggered = false;
    beforeAll(() => {
      vi.useFakeTimers();
      setInterval(()=>{
        triggered = true;
      }, 1000)
    });
    afterAll(() => {
      vi.useRealTimers();
    });
    it.only('Should trigger the timer', () => {
      vi.advanceTimersByTime(1000);
      expect(triggered).toEqual(true); // Fails. triggered = false here
    });
  });
```
Working with setTimeout
```
  describe('Testing timers', () => {
    let triggered = false;
    beforeAll(() => {
      vi.useFakeTimers();
      setTimeout(()=>{
        triggered = true;
      }, 1000)
    });
    afterAll(() => {
      vi.useRealTimers();
    });
    it.only('Should trigger the timer', () => {
      vi.advanceTimersByTime(1000);
      expect(triggered).toEqual(true); // Successful.
    });
  });
```

Reproduction - https://stackblitz.com/edit/github-agxb9y-xks33q?file=test%2Fapp.nuxt.spec.ts
Works without nuxt - https://stackblitz.com/edit/vitest-dev-vitest-hr7i1i?file=test%2Ftimer.test.ts

### Describe the bug

`setInterval` isn't triggering with `fakeTimer`, however `setTimeout` does. I have tried `advanceTimersByTime`, `advanceTimersToNextTimer` and `runAllTimers` but doesn't help.

Note - I don't find this issue with the Vitest itself. using `defineVitestConfig` is causing this behaviour.

**Comment by gsamal** [comment]
When I tried with `window.setInterval`, this works. As per the above reference, it seems like we have defined our own `setInterval`. Is there any config in the nuxt to prevent that?

**Comment by cuixiaorui** [comment]
Using window.setInterval is definitely not a good idea. 
If users are not familiar with Nuxt's implementation details, they will be very confused about why tests fail when using setInterval. 
Before seeing this issue, I spent a lot of time debugging this problem.
If Nuxt has wrapped the original setInterval, then this issue should be handled properly to allow users to directly call setInterval.
