### ISSUE TITLE
There is no way to change the properties in the data in the options api using mountSuspended

### ISSUE THREAD

**Issue by bason8800** [nuxt/test-utils#973]
### Environment

- Operating System: Darwin
- Node Version: v18.20.3
- Nuxt Version: 3.13.2
- CLI Version: 3.13.2
- Nitro Version: 2.9.7
- Package Manager: npm@10.2.3
- Builder: -
- User Config: -
- Runtime Modules: -
- Build Modules: -

### Reproduction

https://stackblitz.com/edit/github-5nd3gu

### Describe the bug

Here is the component using the Options API.

```vue
<script lang="ts">
export default defineNuxtComponent({
  name: "test",
  data() {
    return {
      test: 123
    }
  },
})
</script>

<template>
  <div>{{ test }}</div>
</template>
```

When I try to change data using `setData`, an error is shown with - **TypeError: Cannot add property test, object is not extensible**

```javascript
it('text should be 456', async () => {
  const wrapper = await mountSuspended(Test)

  await wrapper.setData({
    test: 456
  })
  
  expect(wrapper.find('div').text()).toBe('456')
})
```

When I try to change data directly, nothing happens

```javascript
it('text should be 456', async () => {
  const wrapper = await mountSuspended(Test)

  wrapper.vm.test = 456

  await wrapper.vm.$nextTick()
  
  // still 123
  expect(wrapper.find('div').text()).toBe('456')
})
```

### Additional context

`@vue/test-utils` doesn't have this issue.

### Logs

stdout | test/app.nuxt.spec.js
<Suspense> is an experimental feature and its API will likely change.

 ❯ test/app.nuxt.spec.js (2)
   × text should be 456
   × text should be 456

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Failed Tests 2 ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯

 FAIL  test/app.nuxt.spec.js > text should be 456
AssertionError: expected '123' to be '456' // Object.is equality

Expected: "456"
Received: "123"

 ❯ eval test/app.nuxt.spec.js:12:38
     10|   await wrapper.vm.$nextTick();
     11| 
     12|   expect(wrapper.find('div').text()).toBe('456');
       |                                      ^
     13| });
     14| 

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[1/2]⎯

 FAIL  test/app.nuxt.spec.js > text should be 456
TypeError: Cannot add property test, object is not extensible
 ❯ eval node_modules/@vue/test-utils/dist/vue-test-utils.cjs.js:262:25
    260|         }
    261|         else {
    262|             target[key] = sourceValue;
       |                         ^
    263|         }
    264|     });
 ❯ mergeDeep node_modules/@vue/test-utils/dist/vue-test-utils.cjs.js:249:10
 ❯ VueWrapper.setData node_modules/@vue/test-utils/dist/vue-test-utils.cjs.js:7766:9
 ❯ eval test/app.nuxt.spec.js:21:17

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[2/2]⎯

 Test Files  1 failed (1)
      Tests  2 failed (2)
   Start at  14:34:00
   Duration  7.43s (transform 758ms, setup 859ms, collect 674ms, tests 23ms, environment 1.15s, prepare 2.02s)

**Comment by wattanx** [comment]
This is the same as https://github.com/nuxt/test-utils/issues/735. Please track that issue instead.
