### ISSUE TITLE
Importing vi from vitest requires ';' at the end of the line.

### ISSUE THREAD

**Issue by vitorCamarotto** [nuxt/test-utils#987]
### Environment

Nuxt project info:                                                                                                                                                                                                      12:50:22 PM

------------------------------
- Operating System: Linux
- Node Version:     v20.18.0
- Nuxt Version:     3.13.2
- CLI Version:      3.14.0
- Nitro Version:    2.9.7
- Package Manager:  npm@10.8.2
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

Try to run the following spec with vitest

```
// the line with ; works:
import { describe, it, expect, vi } from 'vitest';

// the line without ; breaks:
// import { describe, it, expect, vi } from 'vitest' 

import { mockNuxtImport } from '@nuxt/test-utils/runtime'
import { nextTick } from 'vue'

const { navigateToMock } = vi.hoisted(() => {
  return {
    navigateToMock: vi.fn(),
  }
})

mockNuxtImport('navigateTo', () => {
  return navigateToMock
})

describe('ConfirmView', () => {
  it('does not navigate to /', async () => {
    await nextTick()
    expect(navigateToMock).not.toHaveBeenCalled()
  })
})
```

### Describe the bug

Running vitest requires `;` at the end of the import line, when importing `vi`, and using `mockNuxtImport`.

example: 
```bash
import { describe, it, expect, beforeEach, vi } from 'vitest'; // Works
import { describe, it, expect, beforeEach, vi } from 'vitest' // Does not work
```

If I don't include `;`, I get the following error:
```
Error: Expected ';', got 'vi'
 ❯ getRollupError node_modules/rollup/dist/es/shared/parseAst.js:395:41
 ❯ convertProgram node_modules/rollup/dist/es/shared/parseAst.js:1083:26
 ❯ parseAstAsync node_modules/rollup/dist/es/shared/parseAst.js:2069:106
 ❯ ssrTransformScript node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:52319:11
```

All my other imports can stay without `;`. And this only happens when I import `vi`, importing `describe`, `it`, etc does not break.

Simply adding `;` to the end of the line makes all tests go green.

https://github.com/user-attachments/assets/b6c7f0d1-10a4-4e08-9b39-8f9a29241c44

**Comment by wattanx** [comment]
I tried the same code, but no error occurred. Could you provide a minimal production?
https://stackblitz.com/edit/github-u7ceen

**Comment by vitorCamarotto** [comment]
Couldn't create a minimal reproduction... Maybe it's some config related to eslint / prettier...

**Comment by ezhyrlitsyna** [comment]
I have the same issue. Thanks for very much to share the reason of why this error appear
